from .Detection.Object_detection import ObjectDetection
from .Segmentation.Lane_segmentation import LaneSegmentation
from .Language.EmergencyRecognizer import EmergencyRecognizer
from .Recognition.Drowse_detection import DrowseDetection
from .Language.VoiceIdentification import VoiceRecognizer